datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://host.docker.internal:9090
        isDefault: true
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: Continuum
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": {
                  "type": "grafana",
                  "uid": "-- Grafana --"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 5,
          "links": [],
          "liveNow": false,
          "panels": [
            {
              "collapsed": false,
              "gridPos": {
                "h": 1,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "id": 4,
              "panels": [],
              "title": "Development",
              "type": "row"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "thresholds"
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unitScale": true
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 1
              },
              "id": 2,
              "options": {
                "colorMode": "value",
                "graphMode": "none",
                "justifyMode": "auto",
                "orientation": "auto",
                "reduceOptions": {
                  "calcs": [
                    "lastNotNull"
                  ],
                  "fields": "",
                  "values": false
                },
                "showPercentChange": false,
                "textMode": "auto",
                "wideLayout": true
              },
              "pluginVersion": "10.3.3",
              "targets": [
                {
                  "datasource": "Prometheus",
                  "editorMode": "code",
                  "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"development\"}) by (deployment)",
                  "instant": false,
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "Replicas dev"
                }
              ],
              "title": "Continuum replicas",
              "type": "stat"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "Continuum replicas",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "noValue": "0",
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unitScale": true
                },
                "overrides": [
                  {
                    "__systemRef": "hideSeriesFrom",
                    "matcher": {
                      "id": "byNames",
                      "options": {
                        "mode": "exclude",
                        "names": [
                          "continuum"
                        ],
                        "prefix": "All except:",
                        "readOnly": true
                      }
                    },
                    "properties": [
                      {
                        "id": "custom.hideFrom",
                        "value": {
                          "legend": false,
                          "tooltip": false,
                          "viz": true
                        }
                      }
                    ]
                  }
                ]
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 1
              },
              "id": 5,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": false
                },
                "tooltip": {
                  "mode": "single",
                  "sort": "none"
                }
              },
              "pluginVersion": "10.3.3",
              "targets": [
                {
                  "datasource": "Prometheus",
                  "editorMode": "code",
                  "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"development\"}) by (deployment)",
                  "instant": false,
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "Replicas dev"
                }
              ],
              "title": "Over time",
              "type": "timeseries"
            },
            {
              "collapsed": false,
              "gridPos": {
                "h": 1,
                "w": 24,
                "x": 0,
                "y": 9
              },
              "id": 3,
              "panels": [],
              "title": "Production",
              "type": "row"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "thresholds"
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unitScale": true
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 10
              },
              "id": 1,
              "options": {
                "colorMode": "value",
                "graphMode": "none",
                "justifyMode": "auto",
                "orientation": "auto",
                "reduceOptions": {
                  "calcs": [
                    "lastNotNull"
                  ],
                  "fields": "",
                  "values": false
                },
                "showPercentChange": false,
                "textMode": "auto",
                "wideLayout": true
              },
              "pluginVersion": "10.3.3",
              "targets": [
                {
                  "datasource": "Prometheus",
                  "editorMode": "code",
                  "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"production\"}) by (deployment)",
                  "instant": false,
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "Replicas production"
                }
              ],
              "title": "Continuum replicas",
              "type": "stat"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisBorderShow": false,
                    "axisCenteredZero": false,
                    "axisColorMode": "text",
                    "axisLabel": "Continuum replicas",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "insertNulls": false,
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "noValue": "0",
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green"
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unitScale": true
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 10
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom",
                  "showLegend": false
                },
                "tooltip": {
                  "mode": "single",
                  "sort": "none"
                }
              },
              "pluginVersion": "10.3.3",
              "targets": [
                {
                  "datasource": "Prometheus",
                  "editorMode": "code",
                  "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"production\"}) by (deployment)",
                  "instant": false,
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "Replicas production"
                }
              ],
              "title": "Continuum replicas",
              "type": "timeseries"
            }
          ],
          "refresh": "",
          "schemaVersion": 39,
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-3h",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "",
          "title": "Replicas Dashboard",
          "uid": "ee91e8ac-8dfe-45c4-a748-4fb3f8d9c6e3",
          "version": 5,
          "weekStart": ""
        }

alerting:
  rules.yaml:
    apiVersion: 1
    groups:
      - orgId: 1
        name: Replicas checker
        folder: Continuum
        interval: 30s
        rules:
          - uid: afa74065-eb72-4909-9f11-805b4cfffeb5
            title: Replicas alert - Production
            condition: Replica threshold
            data:
              - refId: Replica metric
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: sum(kube_deployment_status_replicas_available{namespace=~"production"}) by (deployment)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: Replica metric
              - refId: Replica threshold
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 2
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: [ ]
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: Replica metric
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: Replica threshold
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 30s
            annotations:
              description: "Replicas for production environment are below the threshold"
              summary: "Wrong replicas number, possible issue"
            labels: { }
            isPaused: false
          - uid: bb43cc6b-27bf-43e2-8023-951a170b9919
            title: Replicas alert - Development
            condition: Replica threshold
            data:
              - refId: Replica metric
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: sum(kube_deployment_status_replicas_available{namespace=~"development"}) by (deployment)
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: Replica metric
              - refId: Replica threshold
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 2
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: [ ]
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: Replica metric
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: Replica threshold
                  type: threshold
            noDataState: NoData
            execErrState: Error
            for: 30s
            annotations:
              description: "Replicas for development environment are below the threshold"
              summary: "Wrong replicas number, possible issue"
            labels: { }
            isPaused: false
