apiVersion: v1
kind: Service
metadata:
  name: program_name-service
  namespace: production
spec:
  selector:
    app: program_name
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: program_name
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: program_name
  template:
    metadata:
      labels:
        app: program_name
    spec:
      containers:
        - name: program_name
          image: image_name
          ports:
            - containerPort: 8080