pipeline {
  environment {
    registryCredential = 'dockerhub_id'
    dockerImage = ''
  }
  agent { label 'slave' }
  stages {
    stage('Cloning Git') {
      steps {
        git([url: 'git@github.com:AurelDP/Continuum.git', branch: 'main', credentialsId: 'github_id'])
      }
    }
    stage('Building image') {
      steps{
        script {
          dir('dev') {
            def dockerImageName = sh(script: 'mvn help:evaluate -Dexpression=docker.image.name -q -DforceStdout', returnStdout: true).trim()
            def dockerImageTag = sh(script: 'mvn help:evaluate -Dexpression=docker.image.tag -q -DforceStdout', returnStdout: true).trim()
            def jenkinsBuildId = env.BUILD_NUMBER

            sh "docker build --build-arg DOCKER_IMAGE_NAME=${dockerImageName} --build-arg JENKINS_BUILD_ID=${jenkinsBuildId} -t aureldp/${dockerImageName}:${dockerImageTag} ."

            dockerImage = docker.image("aureldp/${dockerImageName}:${dockerImageTag}")
          }
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi ${dockerImage.id}"
      }
    }
  }
}